### PR TITLE
230 bug become provider refresh error

### LINKED ISSUE #230: [Bug]:  Become provider refresh error
### What happened?

A bug happened!

After selecting network and address, on refresh, create MSA button still exists but dropdowns are cleared.
- when you do a regular login, the store doesn't update
- when you go through the Become a Provider flow, the user store updates with your current selections, even though you haven't officially logged in. 
- On refresh, It's showing the create MSA button because it thinks we're at that step, yet the dropdowns aren't loading in the stored data.
- NOTE: you should check all dropdowns and how they handle their values on refresh.

## Expected behavior
- After refresh, dropdowns still contain selected info.

## Demo of bug

https://github.com/user-attachments/assets/cf6b7c19-db1d-4b7b-8e12-80a78a2808e7

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by claireclark1**
## Goal

The goal of this PR is to use the persistent state to keep the dropdowns populated on refresh, resolving the bug.

Closes #230 

## Discussion

To recreate the bug on main:
- go to become a provider
- select network and address
- see create msa or enter provider name
- reload page
- dropdowns are cleared, but create msa/enter provider name persists
- if you go to the values in the store, you'll see that the selected user values are there (which is why we still see the create msa option), but the dropdowns aren't accessing those values.

## Checklist

- [ ] PR Self-Review and Commenting
- [ ] Docs updated
- [ ] Tests added

## Demo

https://github.com/user-attachments/assets/68603d11-8234-446c-a297-1795b13d2c7f

### CODE REVIEW

File: src/components/BecomeAProvider.svelte [hunk 1]
```diff
@@ -10,13 +10,19 @@
   import RequestToBeProvider from '$components/RequestToBeProvider.svelte';
 
   let hasRequestedToBeProvider = $state(false);
+  let newUserInitialVal = $user?.address === '' ? null : $user;
```
Comment (claireclark1) [inline src/components/BecomeAProvider.svelte:13]: The default value is `{address: '', isProvider: false}`. To maintain other logic throughout the app, and display the unselected state in the dropdown, I added this line.

File: src/components/BecomeAProvider.svelte [hunk 2]
```diff
@@ -10,13 +10,19 @@
...
+  let newUser = $state(newUserInitialVal);
+
+  $effect(() => {
+    if (newUser?.address !== '') $user = newUser!;
```
Comment (claireclark1) [inline src/components/BecomeAProvider.svelte:17]: $user needs to be updated here now since it's no longer the bound value.

File: src/components/DropDownMenu.svelte [hunk 3]
```diff
@@ -5,7 +5,7 @@
     label: string;
     id?: string;
     options: T[];
-    value?: T | null;
+    value?: any;
```
Comment (claireclark1) [inline src/components/DropDownMenu.svelte:8]:
```suggestion
    value?: T | null;
```

File: src/components/DropDownMenu.svelte [hunk 4]
```diff
@@ -28,26 +28,26 @@
   }: Props = $props();
 </script>
 
-<div class="column freq-select gap-f8 w-full max-w-[460px]">
```
Comment (claireclark1) [inline src/components/DropDownMenu.svelte:31]: All of the style changes here are because I accidentally merged the wrong thing in a rebase.

File: src/components/SelectNetworkAndAccount.svelte [hunk 5]
```diff
@@ -111,14 +111,30 @@
     }
   }
 
+  function findMatchingAccount(): Account | null {
```
Comment (claireclark1) [inline src/components/SelectNetworkAndAccount.svelte:114]: If we don't have this, the selected value isn't an absolute equal with the options and it shows a blank in dropdown when it should show the selected value.

**Review by mattheworris — APPROVED** [review]
🚢 it!
